export const menu = [
  {
    id: 1,
    title: "main",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icon: "home.svg",
      },
      {
        id: 2,
        title: "Profile",
        url: "/users/1",
        icon: "user.svg",
      },
    ],
  },
  {
    id: 2,
    title: "lists",
    listItems: [
      {
        id: 1,
        title: "Users",
        url: "/users",
        icon: "user.svg",
      },
      {
        id: 2,
        title: "Alerts",
        url: "/alerts",
        icon: "note.svg",
      },
      {
        id: 3,
        title: "Agents",
        url: "/agents",
        icon: "product.svg",
      },
      {
        id: 4,
        title: "Rules",
        url: "/rules",
        icon: "log.svg",
      },
      {
        id: 5,
        title: "Anomalies",
        url: "/anomalies",
        icon: "log.svg",
      },
    ],
  },
  {
    id: 3,
    title: "general",
    listItems: [
      {
        id: 2,
        title: "Notes",
        url: "/notes",
        icon: "note.svg",
      },
      {
        id: 3,
        title: "A.I Bot",
        url: "/bot",
        icon: "note.svg",
      },
    ],
  },
  {
    id: 4,
    title: "Maintenance",
    listItems: [
      {
        id: 1,
        title: "Settings",
        url: "/settings",
        icon: "setting.svg",
      },
    ],
  },
  {
    id: 5,
    title: "analytics",
    listItems: [
      {
        id: 2,
        title: "Report",
        url: "/report",
        icon: "log.svg",
      },
    ],
  },
];

export const topDealUsers = [
  {
    id: 1,
    img: "https://www.colorhexa.com/8b0000.png",
    username: "1752218159.1885",
    email: "Rule: 5501",
    amount: "13",
  },
  {
    id: 2,
    img: "https://www.colorhexa.com/ff9900.png",
    username: "1752218159.7295",
    email: "Rule: 5505",
    amount: "4",
  },
  {
    id: 3,
    img: "https://www.colorhexa.com/ff0000.png",
    username: "1752218442.8936",
    email: "Rule: 1981",
    amount: "8",
  },
  {
    id: 4,
    img: "https://www.colorhexa.com/ff0000.png",
    username: "1752218442.9265",
    email: "Rule: 1004",
    amount: "10",
  },
  {
    id: 5,
    img: "https://www.colorhexa.com/eee900.png",
    username: "1752218666.0127",
    email: "Rule: 1037",
    amount: "1",
  },
  {
    id: 6,
    img: "https://www.colorhexa.com/eee900.png",
    username: "1752218666.1640",
    email: "Rule: 2025",
    amount: "1",
  },
  {
    id: 7,
    img: "https://www.colorhexa.com/eee900.png",
    username: "1752218666.6256",
    email: "Rule: 5202",
    amount: "2",
  },
];

export const chartBoxUser = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title: "Total Users",
  dataKey: "users",
  chartData: [
    { name: "Sun", users: 4 },
    { name: "Mon", users: 6 },
    { name: "Tue", users: 5 },
    { name: "Wed", users: 7 },
    { name: "Thu", users: 4 },
    { name: "Fri", users: 5 },
    { name: "Sat", users: 4 },
  ],
};

export const chartBoxProduct = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title: "Total Agents",
  dataKey: "agents",
  chartData: [
    { name: "Sun", agents: 4 },
    { name: "Mon", agents: 6 },
    { name: "Tue", agents: 5 },
    { name: "Wed", agents: 7 },
    { name: "Thu", agents: 4 },
    { name: "Fri", agents: 5 },
    { name: "Sat", agents: 5 },
  ],
};
export const chartBoxRevenue = {
  color: "steelblue",
  icon: "/revenueIcon.svg",
  title: "Custom Rules",
  dataKey: "rules",
  chartData: [
    { name: "Sun", rules: 6 },
    { name: "Mon", rules: 8 },
    { name: "Tue", rules: 3 },
    { name: "Wed", rules: 2 },
    { name: "Thu", rules: 6 },
    { name: "Fri", rules: 7 },
    { name: "Sat", rules: 3 },
  ],
};
export const chartBoxConversion = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title: "Total Alerts",
  dataKey: "alerts",
  chartData: [
    { name: "Sun", alerts: 3 },
    { name: "Mon", alerts: 7 },
    { name: "Tue", alerts: 5 },
    { name: "Wed", alerts: 9 },
    { name: "Thu", alerts: 4 },
    { name: "Fri", alerts: 6 },
    { name: "Sat", alerts: 4 },
  ]
};

export const alertAnalysisData = [
  {
    name: "Sun",
    critical: 14,
    high: 25,
    medium: 35,
    low: 38,
  },
  {
    name: "Mon",
    critical: 22,
    high: 26,
    medium: 46,
    low: 41,
  },
  {
    name: "Tue",
    critical: 13,
    high: 28,
    medium: 47,
    low: 36,
  },
  {
    name: "Wed",
    critical: 41,
    high: 17,
    medium: 38,
    low: 24,
  },
  {
    name: "Thu",
    critical: 19,
    high: 45,
    medium: 32,
    low: 26,
  },
  {
    name: "Fri",
    critical: 11,
    high: 40,
    medium: 23,
    low: 36,
  },
  {
    name: "Sat",
    critical: 14,
    high: 20,
    medium: 48,
    low: 27,
  },
];

export const barChartBoxAnomaly = {
  title: "Anomalies",
  color: "#ff9800",
  dataKey: "anomaly",
  chartData: [
    { name: "Sun", type: "Logon", anomaly: 5 },
    { name: "Sun", type: "General", anomaly: 7 },
    { name: "Sun", type: "Process", anomaly: 0 },

    { name: "Mon", type: "Logon", anomaly: 4 },
    { name: "Mon", type: "General", anomaly: 8 },
    { name: "Mon", type: "Process", anomaly: 0 },

    { name: "Tue", type: "Logon", anomaly: 6 },
    { name: "Tue", type: "General", anomaly: 4 },
    { name: "Tue", type: "Process", anomaly: 0 },

    { name: "Wed", type: "Logon", anomaly: 7 },
    { name: "Wed", type: "General", anomaly: 5 },
    { name: "Wed", type: "Process", anomaly: 0 },

    { name: "Thu", type: "Logon", anomaly: 3 },
    { name: "Thu", type: "General", anomaly: 3 },
    { name: "Thu", type: "Process", anomaly: 0 },

    { name: "Fri", type: "Logon", anomaly: 6 },
    { name: "Fri", type: "General", anomaly: 2 },
    { name: "Fri", type: "Process", anomaly: 0 },

    { name: "Sat", type: "Logon", anomaly: 4 },
    { name: "Sat", type: "General", anomaly: 2 },
    { name: "Sat", type: "Process", anomaly: 0 },
  ],
};

export const wazuhStatus = {
  isRunning: true, // set to false if unreachable
  version: "4.8.2", // or "Unknown"
};

export const userRows = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Hubbard",
    firstName: "Eula",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Manning",
    firstName: "Stella",
    email: "comhuhmit@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Greer",
    firstName: "Mary",
    email: "ujudokon@hottmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Williamson",
    firstName: "Mildred",
    email: "tinhavabe@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Gross",
    firstName: "Jose",
    email: "gobtagbes@yahoo.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Sharp",
    firstName: "Jeremy",
    email: "vulca.eder@mail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Lowe",
    firstName: "Christina",
    email: "reso.bilic@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Dean",
    firstName: "Garrett",
    email: "codaic@mail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Parsons",
    firstName: "Leah",
    email: "uzozor@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Reid",
    firstName: "Elnora",
    email: "tuhkabapu@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Dunn",
    firstName: "Gertrude",
    email: "gibo@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Williams",
    firstName: "Mark",
    email: "tic.harvey@hotmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/761977/pexels-photo-761977.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Cruz",
    firstName: "Charlotte",
    email: "ceuc@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Harper",
    firstName: "Sara",
    email: "bafuv@hotmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Griffin",
    firstName: "Eric",
    email: "ubi@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
];

export const agents = [
  {
    id: 1,
    img: "https://wazuh.com/uploads/2022/05/WAZUH.png",
    title: "Wazuh",
    status: "Not Connected",
    ip: "192.168.1.1",
    os: "Windows",
    version: "10.0",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.1",
  },
  {
    id: 2,
    img: "https://www.pngmart.com/files/6/Dell-Laptop-PNG-Image.png",
    title: "WinDev2407Eval",
    status: "black",
    ip: "192.168.1.2",
    os: "Windows",
    version: "11",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.2",
  },
  {
    id: 3,
    img: "http://images.samsung.com/is/image/samsung/uk-led-tv-hg40ed670ck-hg40ed670ckxxu-001-front",
    title: "Samsung TV 4K SmartTV",
    status: "gray",
    ip: "192.168.1.3",
    os: "Tizen",
    version: "6.5",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.3",
  },
  {
    id: 4,
    img: "https://raylo.imgix.net/iphone-14-blue.png",
    title: "Apple Iphone 14 Pro Max",
    status: "white",
    ip: "192.168.1.4",
    os: "iOS",
    version: "17",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.4",
  },
  {
    id: 5,
    img: "https://www.signify.com/b-dam/signify/en-aa/about/news/2020/20200903-movie-night-essentials-popcorn-ice-cream-and-the-new-philips-hue-play-gradient-lightstrip/packaging-lighstrip.png",
    title: "Philips Hue Play Gradient",
    status: "rainbow",
    ip: "192.168.1.5",
    os: "Embedded",
    version: "3.1",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.5",
  },
  {
    id: 6,
    img: "https://www.smartworld.it/wp-content/uploads/2019/09/High_Resolution_PNG-MX-Master-3-LEFT-GRAPHITE.png",
    title: "Logitech MX Master 3",
    status: "black",
    ip: "192.168.1.6",
    os: "Firmware",
    version: "1.9.2",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.6",
  },
  {
    id: 7,
    img: "https://www.pngarts.com/files/7/Podcast-Mic-PNG-Picture.png",
    title: "Rode Podcast Microphone",
    status: "gray",
    ip: "192.168.1.7",
    os: "N/A",
    version: "N/A",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.7",
  },
  {
    id: 8,
    img: "https://5.imimg.com/data5/SW/VM/MY-5774620/toshiba-split-ac-2-ton-3-star-rated-ras-24s3ks-500x500.png",
    title: "Toshiba Split AC 2",
    status: "white",
    ip: "192.168.1.8",
    os: "Embedded",
    version: "2.0",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.8",
  },
  {
    id: 9,
    img: "https://img.productz.com/review_image/102489/preview_sony-kdl-50w800b-50-inch-hdtv-review-superb-picture-102489.png",
    title: "Sony Bravia KDL-47W805A",
    status: "black",
    ip: "192.168.1.9",
    os: "Android TV",
    version: "9.0",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.9",
  },
  {
    id: 10,
    img: "https://venturebeat.com/wp-content/uploads/2015/07/As_AO1-131_gray_nonglare_win10_03.png?fit=1338%2C1055&strip=all",
    title: "Acer Laptop 16 KL-4804",
    status: "black",
    ip: "192.168.1.10",
    os: "Windows",
    version: "10.0",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.10",
  },
];

export const alerts = [
  {
    id: 1,
    title: 1753429089.991,
    timestamp: "25 Jul 2025, 03:38 PM",
    rule: 5501,
    level: 3,
    agent: "wazuh",
    description: "PAM: Login session opened.",
  },
  {
    id: 2,
    title: 1753429090.123,
    timestamp: "25 Jul 2025, 03:40 PM",
    rule: 4502,
    level: 5,
    agent: "wazuh",
    description: "Unauthorized file access detected.",
  },
  {
    id: 3,
    title: 1753429091.456,
    timestamp: "25 Jul 2025, 03:45 PM",
    rule: 6503,
    level: 2,
    agent: "wazuh",
    description: "Firmware update started.",
  },
  {
    id: 4,
    title: 1753429092.789,
    timestamp: "25 Jul 2025, 03:50 PM",
    rule: 5604,
    level: 4,
    agent: "wazuh",
    description: "iOS system integrity violation.",
  },
  {
    id: 5,
    title: 1753429093.111,
    timestamp: "25 Jul 2025, 03:55 PM",
    rule: 7705,
    level: 1,
    agent: "wazuh",
    description: "Lightstrip disconnected.",
  },
  {
    id: 6,
    title: 1753429094.222,
    timestamp: "25 Jul 2025, 04:00 PM",
    rule: 8806,
    level: 3,
    agent: "wazuh",
    description: "Firmware patch applied.",
  },
  {
    id: 7,
    title: 1753429095.333,
    timestamp: "25 Jul 2025, 04:05 PM",
    rule: 9907,
    level: 2,
    agent: "wazuh",
    description: "Microphone muted remotely.",
  },
  {
    id: 8,
    title: 1753429096.444,
    timestamp: "25 Jul 2025, 04:10 PM",
    rule: 10008,
    level: 4,
    agent: "wazuh",
    description: "AC temperature threshold exceeded.",
  },
  {
    id: 9,
    title: 1753429097.555,
    timestamp: "25 Jul 2025, 04:15 PM",
    rule: 11009,
    level: 5,
    agent: "wazuh",
    description: "Unauthorized HDMI connection.",
  },
  {
    id: 10,
    title: 1753429098.666,
    timestamp: "25 Jul 2025, 04:20 PM",
    rule: 12010,
    level: 3,
    agent: "wazuh",
    description: "Windows Defender scan completed.",
  },
];

export const singleUser = {
  id: 1,
  title: "John Doe",
  img: "https://images.pexels.com/photos/17397364/pexels-photo-17397364.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  info: {
    username: "Johndoe99",
    fullname: "John Doe",
    email: "johndoe@gmail.com",
    phone: "123 456 789",
    status: "verified",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "clicks", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        clicks: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        clicks: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        clicks: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        clicks: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        clicks: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        clicks: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        clicks: 4300,
      },
    ],
  },
  activities: [
    {
      text: "John Doe purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "John Doe added 3 items into their wishlist",
      time: "1 week ago",
    },
    {
      text: "John Doe purchased Sony Bravia KD-32w800",
      time: "2 weeks ago",
    },
    {
      text: "John Doe reviewed a product",
      time: "1 month ago",
    },
    {
      text: "John Doe added 1 items into their wishlist",
      time: "1 month ago",
    },
    {
      text: "John Doe reviewed a product",
      time: "2 months ago",
    },
  ],
};

export const singleAgent = {
  id: 1,
  title: "Wazuh",
  img: "https://wazuh.com/uploads/2022/05/WAZUH.png",
  info: {
    status: "Not Connected",
    ip: "192.168.1.1",
    os: "Windows",
    version: "10.0",
    registeredDate: "2023-02-01",
    lastSeen: "2023-07-20",
    registeredIP: "192.168.1.1",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "orders", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        orders: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        orders: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        orders: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        orders: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        orders: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        orders: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        orders: 4300,
      },
    ],
  },
  activities: [
    {
      text: "John Doe purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "Jane Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 week ago",
    },
    {
      text: "Mike Doe purchased Playstation 5 Digital Edition",
      time: "2 weeks ago",
    },
    {
      text: "Anna Doe reviewed the product",
      time: "1 month ago",
    },
    {
      text: "Michael Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 month ago",
    },
    {
      text: "Helen Doe reviewed the product",
      time: "2 months ago",
    },
  ],
};

export const singleAlert = {
  id: 1,
  title: "1753429089.991",
  info: {
    timestamp: "25 Jul 2025, 03:38 PM",
    rule: "5501",
    level: "3",
    agent: "wazuh",
    description: "PAM: Login session opened.",
  }, 
  chart: {
    dataKeys: [
      { name: "critical", color: "#8B0000" },
      { name: "high", color: "#FF0000" },
      { name: "medium", color: "#ff9900" },
      { name: "low", color: "#eee900" },
    ],
    data: [
      {
        name: "Sun",
        critical: 7,
        high: 3,
        medium: 2,
        low: 1,
      },
      {
        name: "Mon",
        critical: 6,
        high: 5,
        medium: 3,
        low: 2,
      },
      {
        name: "Tue",
        critical: 4,
        high: 6,
        medium: 2,
        low: 3,
      },
      {
        name: "Wed",
        critical: 5,
        high: 4,
        medium: 3,
        low: 2,
      },
      {
        name: "Thu",
        critical: 3,
        high: 5,
        medium: 4,
        low: 1,
      },
      {
        name: "Fri",
        critical: 6,
        high: 3,
        medium: 2,
        low: 2,
      },
      {
        name: "Sat",
        critical: 4,
        high: 4,
        medium: 5,
        low: 3,
      },
    ],
  },
  activities: [
    {
      text: "John Doe purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "Jane Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 week ago",
    },
    {
      text: "Mike Doe purchased Playstation 5 Digital Edition",
      time: "2 weeks ago",
    },
    {
      text: "Anna Doe reviewed the product",
      time: "1 month ago",
    },
    {
      text: "Michael Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 month ago",
    },
    {
      text: "Helen Doe reviewed the product",
      time: "2 months ago",
    },
  ],
};